---
- name: Check if database exists 
  command: /opt/vertica/bin/admintools -t list_db -d mon
  sudo_user: dbadmin
  ignore_errors: yes
  register: create_database

- name: Create database 
  command: /opt/vertica/bin/admintools -t create_db -s {{vertica_ips}} -d mon -p password
  sudo_user: dbadmin
  environment: "{{env}}"
  when: create_database|failed

- name: Set restart policy
  command: /opt/vertica/bin/admintools -t set_restart_policy -d mon -p always 
  sudo_user: dbadmin
  environment: "{{env}}"

- name: Check if ssl links exists
  stat: path={{vertica_catalog_dir}}/mon/v_mon_node0001_catalog/server.key
  register: ssl_link_status

- name: Create Links
  shell: ln /var/vertica/server* /var/vertica/catalog/mon/v*/
  when: not ssl_link_status.stat.exists

- name: Restart the db is the links were created
  command: "{{ item }}"
  sudo_user: dbadmin
  with_items:
    - /opt/vertica/bin/admintools -t stop_db -F -p password -d mon
    - /opt/vertica/bin/admintools -t start_db -p password -d mon
  when: not ssl_link_status.stat.exists
