---
# It is important that the dbadmin users on each node in a cluster can have passwordless ssh access to the other machines
# This is done with a shared private ssh key

- name: Create dbadmin group
  group: name="{{vertica_dbadmin_group}}" state=present

- name: Create dbadmin user
  user: name="{{vertica_dbadmin_user}}" home="{{vertica_dbadmin_home}}" group="{{vertica_dbadmin_group}}"

- name: Create ssh directory in vertica home directory
  file: path="{{vertica_dbadmin_home}}"/.ssh owner="{{vertica_dbadmin_user}}" group="{{vertica_dbadmin_group}}" mode=0700 state=directory

- name: Create config for ssh 
  copy: dest={{vertica_dbadmin_home}}/.ssh/config owner="{{vertica_dbadmin_user}}" group="{{vertica_dbadmin_group}}" mode=0600 content="StrictHostKeyChecking no" force=no

- name: Create id_rsa
  copy: dest={{vertica_dbadmin_home}}/.ssh/id_rsa owner="{{vertica_dbadmin_user}}" group="{{vertica_dbadmin_group}}" mode=0600 content="{{ssh_private_key.content| b64decode}}" force=no

- name: Create id_rsa.pub
  copy: dest={{vertica_dbadmin_home}}/.ssh/id_rsa.pub owner="{{vertica_dbadmin_user}}" group="{{vertica_dbadmin_group}}" mode=0600 content="{{ssh_public_key.content| b64decode}}" force=no

- name: Add public key to authorized keys
  authorized_key: user="{{vertica_dbadmin_user}}" key="{{ssh_public_key.content| b64decode}}"

- name: Create user directory under vertica for dbadmin
  file: path=/opt/vertica/config/users/"{{vertica_dbadmin_user}}" owner="{{vertica_dbadmin_user}}" group=root mode=0775 state=directory

- name: Create agent.conf
  file: path=/opt/vertica/config/users/"{{vertica_dbadmin_user}}"/agent.conf owner=root group=root mode=0644 state=touch

